#include "libmatrix.h"
#include "ft_dimensions_equal.c"
#include "ft_matrix_add_double.c"
#include "ft_matrix_free.c"
#include "ft_matrix_id.c"
#include "ft_matrix_mul_double.c"
#include "ft_matrix_mul_vector.c"
#include "ft_matrix_mul.c"
#include "ft_matrix_new.c"
#include "ft_matrix_scale.c"
#include "ft_matrix_set_all.c"
#include "ft_matrix_set_vals.c"
#include "ft_matrix_sub_double.c"
#include "ft_matrix_sub.c"
#include "ft_puterror.c"
#include "ft_putint_fd.c"
#include "ft_putint.c"
#include "ft_putmatrix.c"
#include "ft_putstr_fd.c"
#include "ft_putvector.c"
#include "ft_scale_matrix.c"
#include "ft_vector_add.c"
#include "ft_vector_cross.c"
#include "ft_vector_dot.c"
#include "ft_vector_dup.c"
#include "ft_vector_forward.c"
#include "ft_vector_free.c"
#include "ft_vector_mag.c"
#include "ft_vector_new.c"
#include "ft_vector_normalize.c"
#include "ft_vector_scale.c"
#include "ft_vector_set_all.c"
#include "ft_vector_set_vals.c"
#include "ft_vector_sub.c"
#include "ft_vector_to_matrix.c"
#include "ft_vector4_new.c"

int main()
{
    t_matrix *mat = ft_matrix_id(3,3);
    ft_putmatrix(mat);
}